export default [
  {
    index:"1",
    title:"导航1",
    hasChild:true,
    child:[
      {
        index:"1-1",
        title:"导航1-1",
        hasChild:false
      }
    ]
  },
  {
    index:"2",
    title:"导航2",
    hasChild:false,
  },
  {
    index:"/freeTravel",
    title:"自由行",
    hasChild:true,
    child:[
      {
        index:"/country",
        title:"国家",
        hasChild:false
      },
      {
        index:"/country/province",
        title:"省份",
        hasChild:false
      },
      {
        index:"/country/province/city",
        title:"城市",
        hasChild:false
      }
    ]
  }
]
